name: wander-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - boto3
      - openai
      - requests
      - aws-lambda-powertools
      - aws-sam-cli
      - pytest
      - python-dotenv
